
export const FETCH_COMMENTAIRES_REQUEST = 'FETCH_COMMENTAIRES_REQUEST';
export const FETCH_COMMENTAIRES_SUCCESS = 'FETCH_COMMENTAIRES_SUCCESS';
export const FETCH_COMMENTAIRES_FAILURE = 'FETCH_COMMENTAIRES_FAILURE';

export const  ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const  ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';