export const UPDATE_REALISATION_REQUEST = 'UPDATE_REALISATION_REQUEST';
export const UPDATE_REALISATION_SUCCESS = 'UPDATE_REALISATION_SUCCESS';
export const UPDATE_REALISATION_FAILURE = 'UPDATE_REALISATION_FAILURE';